name: Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ '21', '23' ] # Make matrix cover more vendors, languages and timezones
        vendor: ['oracle']

    name: Build with JDK ${{ matrix.version }} - ${{ matrix.vendor }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Gradle Build
        run: ./gradlew build -Dmatrix.version=${{ matrix.version }} -Dmatrix.vendor=${{ matrix.vendor }}